### ISSUE TITLE
本地开发正常，打包后会报错？CJS和ESM都尝试过了

### ISSUE THREAD

**Issue by Shawnqqq** [ota-meshi/vuepress2-plugin-full-text-search#22]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/51352436/169809901-6e71bfac-8701-4b5c-ad2d-173967e9e321.png">

**Comment by ota-meshi** [comment]
わたしはあなたが何を言っているかわからないのでこのissueを閉じます。issueを開く際は画像を使用せずに詳細を書いてください。また問題を再現するための最小のリポジトリを共有してください。
