### ISSUE TITLE
file path separator incorrect on windows

### ISSUE THREAD

**Issue by stainge** [ota-meshi/vuepress2-plugin-full-text-search#5]
![image](https://user-images.githubusercontent.com/48624558/155694709-26d13c62-8c64-4a38-99d9-de5981c0a8ed.png)

**Comment by ota-meshi** [comment]
I don't use windows.  Would you please open a PR if you know how to fix it?

**Comment by stainge** [comment]
> I don't use windows. Would you please open a PR if you know how to fix it?

I think this could be similar to [ [Bug report] Window 11 can't start dev server ](https://github.com/vuepress/vuepress-next/issues/364) , but I could't fix it, so I opened this issue.
