### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by 782042369** [ota-meshi/vuepress2-plugin-full-text-search#8]
Compiling with vite'UPD_NAME' is not exported by docs/.vuepress/.temp/internal/vuepress2-plugin-full-text-search-search-index.js, imported by node_modules/vuepress2-plugin-full-text-search/lib/client/engine.js

 "vuepress": "^2.0.0-beta.36",
"vuepress2-plugin-full-text-search": "^0.1.0"

**Comment by ota-meshi** [comment]
Thank you for posting this issue.
I'm not using vuepress with vite (in which case I use vitepress). Can you share your repository that can reproduce your problem?

**Comment by 782042369** [comment]
demo: https://github.com/782042369/vuepress-demo

**Comment by 782042369** [comment]
npm > 14

**Comment by ota-meshi** [comment]
I can't access your repository.
<img width="511" alt="image" src="https://user-images.githubusercontent.com/16508807/158502183-1218bc80-fce0-46bc-b402-7f56435e6e52.png">

**Comment by 782042369** [comment]
soory，change public。

**Comment by ota-meshi** [comment]
Thank you for sharing the repository. I found the cause.
